language: go

sudo: false
go:
  - 1.4

before_install:
  - go get
  - go get github.com/rocky/go-buildutil
  - go get github.com/rocky/go-astutil
  - (cd interp && go get)
  - (cd terminal && go get)
  - (cd gub && go get)
  - (cd cmd && go get)
  - (cd gub/cmd && go get)

script:
  - go test -v
  - (cd interp && go test -v)
  - (cd cmd && go build tortoise.go)
  - (cd trepan && go build)
  - (cd gub && go test -v)
