language: go

go:
  - tip
  - 1.2

script:
  - go get "code.google.com/p/go.tools/go/exact"
  - go get "github.com/rocky/go-types"
  - go get "github.com/rocky/go-types/typemap"
  - go get "github.com/rocky/go-importer"
  - go get "github.com/davecgh/go-spew"
  - go test -v
  - cd interp
  - go test -v
  - cd ..
  - go get "code.google.com/p/go-gnureadline"
  - go get "code.google.com/p/go-columnize"
  - go get "github.com/mgutz/ansi"
  - go get "github.com/rocky/go-eval"
  # - go get "github.com/rocky/go-fish"
  - go build tortoise.go
  - cd gub
  - go build
  - go test -v
